### ISSUE TITLE
Add scatterplot, topic_model, load_data to notebook tests

### ISSUE THREAD

**Issue by truongc2** [data-describe/data-describe#184]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

**Related Issues**
*List any relevant issues if this request is related to a bug*

**Desired Change**
*Describe what you would like to happen*

**Alternatives Considered**
*Describe any alternative solutions you've already considered*

**Additional Info**
*Provide any additional information on context*

**Comment by haishiro** [comment]
Resolved in #224
