### ISSUE TITLE
User Guide/Optional Dependencies has an extra cell

### ISSUE THREAD

**Issue by haishiro** [data-describe/data-describe#349]
Your bug may already be reported!
Please search on the [issue tracker](../issues?q=label%3Abug+is%3Aissue) before creating one.

**Description**

![image](https://user-images.githubusercontent.com/11744859/95923585-6d404880-0d7b-11eb-885e-60badf96f9a7.png)

**Steps to Reproduce**

**Your Environment**
* data describe version:
* Python version:
* Operating System:

**Comment by zack-soenen** [comment]
Closed as a part of PR 394
