### ISSUE TITLE
Create example notebooks for more specific use cases

### ISSUE THREAD

**Issue by truongc2** [data-describe/data-describe#450]
Your request may already be reported!
Please search on the [issue tracker](../?q=label%3Aenhancement+is%3Aissue) before creating one.

**Desired Change**

Example notebooks for sensor data, predictive maintenance, etc.

**Additional Info**

**Comment by haishiro** [comment]
@truongc2 how is this different from #449 ?

**Comment by truongc2** [comment]
> @truongc2 how is this different from #449 ?

Created by mistake. Thought this issue didn't go through when submitted originally.
