### ISSUE TITLE
data_summary: Unexpected keyword error when running Data_Summary.ipynb in the examples folder

### ISSUE THREAD

**Issue by ankur-srivastava1** [data-describe/data-describe#451]
Your bug may already be reported!
Please search on the [issue tracker](../issues?q=label%3Abug+is%3Aissue) before creating one.

**Description**
Unexpected keyword argument error with as_percentage and auto_float arguments.

**Steps to Reproduce**

**Your Environment**
* data describe version:
* Python version:
* Operating System:

**Comment by haishiro** [comment]
Could you share your data-describe version (`pip list`) and python version?

**Comment by ankur-srivastava1** [comment]
data-describe                      0.1.0a1
Python 3.7.6

**Comment by haishiro** [comment]
Those parameters were added in 0.1.0b3

https://github.com/data-describe/data-describe/releases/tag/v0.1.0b3

**Comment by ankur-srivastava1** [comment]
So I re-installed data_describe with pip. That should install the latest version. But my version remains as 0.1.0a1. Is this the latest version?

**Comment by ankur-srivastava1** [comment]
Nevermind.  pip install data_describe==0.1.0b3 works. I see this version is in pre-release which is why just pip install data_describe didnt work earlier.
